deployment:
  replicas: 2
  imageVersion: 1.0.0 #IMAGE_VERSION
  imageURL: vanimina/frontend #315069654700.dkr.ecr.us-east-1.amazonaws.com/roboshop/dev/frontend
hpa:
  cpuUtilization: 15
#tgb:
  #arn: arn:aws:elasticloadbalancing:us-east-1:315069654700:targetgroup/roboshop-dev/5b208a7c17721cb9